architectury {
    common("fabric", "quilt")
}

dependencies {
    compileOnly "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modCompileOnly "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    compileOnly(project(path: ':common', configuration: 'namedElements')) { transitive false }

    modImplementation "de.erdbeerbaerlp:dcintegration.common:$rootProject.core_version"

    modImplementation("me.lucko:fabric-permissions-api:$rootProject.fabric_permissions_api")
    modImplementation "eu.pb4:placeholder-api:$rootProject.placeholder_api"

    //Styled Chat
    modCompileOnly "maven.modrinth:styled-chat:$rootProject.styled_chat"

    //Dynmap-API
    modCompileOnly('com.github.webbukkit:DynmapCoreAPI:2.5')

    //Vanish
    modCompileOnly "maven.modrinth:vanish:$rootProject.vanish"
}
repositories {
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven { url "https://maven.nucleoid.xyz/" }

    maven { url 'https://jitpack.io' }
}

processResources {
    inputs.property "minecraft_version", rootProject.minecraft_version

    filesMatching("fabric-like.dcintegration.mixins.json") {
        expand "minecraft_version": rootProject.minecraft_version
    }
}

loom {
    mixin {
        defaultRefmapName = "dcintegration-fabric-MC${project.property('minecraft_version')}-fabric-refmap.json"
    }
}