# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 3.1.1
core_version = 3.1.0
releaseType = BETA
changelog = Fix advancement channel bug, Fix vanilla command permission issue


maven_group = de.erdbeerbaerlp.dcintegration.architectury
archives_name = dcintegration
enabled_platforms = fabric,forge,neoforge

# Minecraft properties
minecraft_version = 1.21.11

# Dependencies
fabric_loader_version = 0.18.4
fabric_api_version = 0.141.2+1.21.11
neoforge_version = 21.11.37-beta
forge_version = 1.21.11-61.0.8

# Fabric Dependencies
fabric_permissions_api = 0.6.1
placeholder_api = 2.8.2+1.21.10
styled_chat = 2.11.0+1.21.11
vanish = 1.6.1+1.21.10
# TODO: vanish 1.6.6 built in loom 1.14, cannot update since architectury loom is only 1.13

# NeoForge Dependencies
vanishmod = ntqQP0fn