# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 3.2.0
core_version = 3.1.0
releaseType = RELEASE
changelog = Update to 26.1.2


maven_group = de.erdbeerbaerlp.dcintegration
archives_name = dcintegration

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.19.2
fabric_api_version=0.146.1+26.1.2

# Fabric Dependencies
fabric_permissions_api = 0.7.0
placeholder_api = 3.0.0+26.1
styled_chat = 2.12.0-pre.1+26.1
vanish = 1.6.8+26.1

