# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod properties
mod_version = 3.2.0
core_version = 3.2.0
releaseType = BETA
changelog = Port to 26.1.x - Early official port, if there are issues, let me know


maven_group = de.erdbeerbaerlp.dcintegration.architectury
archives_name = dcintegration
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.152.1+26.1.2
neoforge_version = 26.1.2.71

# Fabric Dependencies
fabric_permissions_api = 0.7.0
placeholder_api = 3.0.0+26.1
styled_chat = 2.12.0+26.1.2
vanish = 1.6.14+26.1.2

# NeoForge Dependencies
vanishmod = iVEuBaPo